// packages/vue/src/CommentThread.vue
<template>
  <div class="canopy-thread" :class="className" role="region" aria-label="Comments">
    <div v-if="comments.length === 0" class="canopy-empty">
      {{ emptyStateText }}
    </div>
    <div
      v-else
      ref="scrollEl"
      class="canopy-scroll"
      :style="height !== undefined ? { height: `${height}px` } : undefined"
      tabindex="-1"
      @scroll="handleScroll"
    >
      <div :style="{ paddingTop: `${paddingTop}px`, paddingBottom: `${paddingBottom}px` }">
        <CommentRow
          v-for="item in visibleItems"
          :key="item.comment.id"
          :item="item"
          :indent-width="indentWidth"
          :on-reply="onReply"
          :on-like="onLike"
          :on-collapse="handleCollapse"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import {
  buildTree,
  flattenTree,
  buildNodeMap,
  type RawComment,
  type CollapseState,
} from '@kanopee/core';
import CommentRow from './CommentRow.vue';
import './styles.css';

const props = withDefaults(defineProps<{
  comments: RawComment[];
  indentWidth?: number;
  height?: number;
  estimatedRowHeight?: number;
  emptyStateText?: string;
  className?: string;
  defaultCollapsed?: string[];
  /** Controlled collapse state */
  collapsed?: string[];
  onReply?: (parentId: string, body: string) => void | Promise<void>;
  onLike?: (commentId: string, isLiked: boolean) => void;
  onCollapse?: (commentId: string, collapsed: boolean) => void;
  onScrollEnd?: () => void;
}>(), {
  indentWidth: 24,
  estimatedRowHeight: 80,
  emptyStateText: 'No comments yet. Be the first!',
  className: '',
  defaultCollapsed: () => [],
});

// ── Collapse state ────────────────────────────────────────────────
const internalCollapsed = ref<CollapseState>(new Set(props.defaultCollapsed));

const isControlled = computed(() => props.collapsed !== undefined);
const activeCollapsed = computed<CollapseState>(() =>
  isControlled.value ? new Set(props.collapsed!) : internalCollapsed.value,
);

function handleCollapse(commentId: string, shouldCollapse: boolean) {
  if (!isControlled.value) {
    const next = new Set(internalCollapsed.value);
    if (shouldCollapse) next.add(commentId);
    else next.delete(commentId);
    internalCollapsed.value = next;
  }
  props.onCollapse?.(commentId, shouldCollapse);
}

// ── Tree / flatten ────────────────────────────────────────────────
const forest = computed(() => buildTree(props.comments));
const flatItems = computed(() => flattenTree(forest.value, activeCollapsed.value));

// ── Simple scroll-window virtualizer ─────────────────────────────
const OVERSCAN = 5;

const scrollEl = ref<HTMLDivElement>();
const scrollTop = ref(0);
const containerHeight = ref(0);

const startIdx = computed(() =>
  Math.max(0, Math.floor(scrollTop.value / props.estimatedRowHeight!) - OVERSCAN),
);
const endIdx = computed(() =>
  Math.min(
    flatItems.value.length,
    Math.ceil((scrollTop.value + containerHeight.value) / props.estimatedRowHeight!) + OVERSCAN,
  ),
);
const visibleItems = computed(() => flatItems.value.slice(startIdx.value, endIdx.value));
const paddingTop = computed(() => startIdx.value * props.estimatedRowHeight!);
const paddingBottom = computed(() =>
  Math.max(0, (flatItems.value.length - endIdx.value) * props.estimatedRowHeight!),
);

function handleScroll(e: Event) {
  const el = e.currentTarget as HTMLDivElement;
  scrollTop.value = el.scrollTop;
  containerHeight.value = el.clientHeight;
  if (props.onScrollEnd && el.scrollTop + el.clientHeight >= el.scrollHeight - 40) {
    props.onScrollEnd();
  }
}

onMounted(() => {
  if (scrollEl.value) {
    containerHeight.value = scrollEl.value.clientHeight;
  }
});
</script>

// packages/react/src/CommentThread.tsx
import React, {
  useState,
  useMemo,
  useCallback,
  useRef,
  useEffect,
  CSSProperties,
} from 'react';
import { useVirtualizer } from '@tanstack/react-virtual';
import {
  buildTree,
  flattenTree,
  buildNodeMap,
  type RawComment,
  type FlatItem,
  type CollapseState,
} from '@kanopee/core';
import { CommentRow, type CommentRowCallbacks } from './CommentRow.js';
import './styles.css';

export interface CommentThreadProps extends CommentRowCallbacks {
  /**
   * Custom row renderer. When provided, called instead of the default `<CommentRow>` for every item.
   * Use this to compose your own row from Kanopee primitives.
   *
   * @example
   * renderItem={(item) => <MyCustomRow item={item} />}
   */
  renderItem?: (item: FlatItem) => React.ReactNode;
  /** Flat array of comments. Only `id`, `parentId`, `author`, `body`, and `timestamp` are required. */
  comments: RawComment[];

  /**
   * Pixel width of each indent level.
   * @default 24
   */
  indentWidth?: number;

  /**
   * Fixed height of the scroll container in pixels.
   * If omitted the thread expands to its natural height (no virtualization scroll container).
   * @default undefined
   */
  height?: number;

  /**
   * Estimated row height used by the virtualizer for initial layout.
   * Rows are auto-measured; this only affects the initial scroll position estimate.
   * @default 80
   */
  estimatedRowHeight?: number;

  /**
   * Content rendered when `comments` is empty.
   */
  emptyState?: React.ReactNode;

  /**
   * Additional className applied to the root element.
   */
  className?: string;

  /**
   * Additional inline styles on the root element.
   * Use this to set CSS custom properties, e.g. `{ '--canopy-indent-width': '20px' }`.
   */
  style?: CSSProperties;

  /**
   * IDs of comments whose children should start collapsed.
   * Canopy manages collapse state internally; this is the initial value.
   */
  defaultCollapsed?: string[];

  /**
   * Override the full collapse state from outside (controlled mode).
   * You must also supply `onCollapse` to update it.
   */
  collapsed?: string[];

  /** Called when the user scrolls to the bottom (useful for pagination). */
  onScrollEnd?: () => void;
}

export function CommentThread({
  comments,
  indentWidth = 24,
  height,
  estimatedRowHeight = 80,
  emptyState,
  className,
  style,
  defaultCollapsed,
  collapsed: collapsedProp,
  onReply,
  onLike,
  onCollapse: onCollapseProp,
  onScrollEnd,
  renderItem,
}: CommentThreadProps) {
  // ── Collapse state (uncontrolled or controlled) ──────────────
  const [internalCollapsed, setInternalCollapsed] = useState<CollapseState>(
    () => new Set(defaultCollapsed ?? []),
  );

  const isControlled = collapsedProp !== undefined;
  const collapsed: CollapseState = isControlled
    ? new Set(collapsedProp)
    : internalCollapsed;

  const handleCollapse = useCallback(
    (commentId: string, shouldCollapse: boolean) => {
      if (!isControlled) {
        setInternalCollapsed((prev) => {
          const next = new Set(prev);
          if (shouldCollapse) next.add(commentId);
          else next.delete(commentId);
          return next;
        });
      }
      onCollapseProp?.(commentId, shouldCollapse);
    },
    [isControlled, onCollapseProp],
  );

  // ── Build + flatten tree ──────────────────────────────────────
  const { forest, nodeMap } = useMemo(() => {
    const forest = buildTree(comments);
    const nodeMap = buildNodeMap(forest);
    return { forest, nodeMap };
  }, [comments]);

  const flatItems = useMemo(
    () => flattenTree(forest, collapsed),
    [forest, collapsed],
  );

  // ── Virtualizer ───────────────────────────────────────────────
  const scrollRef = useRef<HTMLDivElement>(null);

  const virtualizer = useVirtualizer({
    count: flatItems.length,
    getScrollElement: () => scrollRef.current,
    estimateSize: () => estimatedRowHeight,
    overscan: 5,
  });

  const virtualItems = virtualizer.getVirtualItems();

  // ── Scroll-end detection ──────────────────────────────────────
  useEffect(() => {
    if (!onScrollEnd) return;
    const el = scrollRef.current;
    if (!el) return;

    function handleScroll() {
      if (!el) return;
      if (el.scrollTop + el.clientHeight >= el.scrollHeight - 40) {
        onScrollEnd?.();
      }
    }

    el.addEventListener('scroll', handleScroll, { passive: true });
    return () => el.removeEventListener('scroll', handleScroll);
  }, [onScrollEnd]);

  // ── Empty state ───────────────────────────────────────────────
  if (comments.length === 0) {
    return (
      <div
        className={['canopy-thread', className].filter(Boolean).join(' ')}
        style={style}
        role="region"
        aria-label="Comments"
      >
        {emptyState ?? (
          <div className="canopy-empty">No comments yet. Be the first!</div>
        )}
      </div>
    );
  }

  const totalHeight = virtualizer.getTotalSize();

  return (
    <div
      className={['canopy-thread', className].filter(Boolean).join(' ')}
      style={style}
      role="region"
      aria-label="Comments"
    >
      <div
        ref={scrollRef}
        className="canopy-scroll"
        style={height !== undefined ? { height } : undefined}
        tabIndex={-1}
      >
        {/* Spacer that establishes total scroll height */}
        <div style={{ height: totalHeight, position: 'relative' }}>
          <div
            style={{
              position: 'absolute',
              top: 0,
              left: 0,
              width: '100%',
              transform: `translateY(${virtualItems[0]?.start ?? 0}px)`,
            }}
          >
            {virtualItems.map((vItem) => {
              const item = flatItems[vItem.index];
              return (
                <div
                  key={item.comment.id}
                  data-index={vItem.index}
                  ref={virtualizer.measureElement}
                >
                  {renderItem ? renderItem(item) : (
                    <CommentRow
                      item={item}
                      indentWidth={indentWidth}
                      onReply={onReply}
                      onLike={onLike}
                      onCollapse={handleCollapse}
                    />
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}
